name: Cypress Tests

on: [push]

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ensure you're using a compatible Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headless: true
