name: Cypress Tests

on: [push]

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ensure you're using a compatible Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          
      - name: Send email notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Cypress Tests Successful"
          body: "All Cypress tests passed successfully!"
          to: ekomobongjohn0228@gmail.com
          from: ekayhally@gmail.com